[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.30", features = ["full"] }
tokio-rustls = "0.23"
rustls = "0.20"
rustls-pemfile = "1.0"
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = "0.3"
anyhow = "1.0"

